logging:
  level:
    org.springframework: debug
# 다국어파일
spring:
  messages:
    basename: messages
  security:
    user:
      name: user
      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"
